### ISSUE TITLE
Players can hear all (could be something with MLOs and radio)

### ISSUE THREAD

**Issue by KrisKingo** [FrazzIe/mumble-voip-fivem#104]
Yeah, so our server have the problem that you can hear players from miles away.
We have already tried the fixes in the other issues about this topic but havent worked.
What we tried:
- Update artifacts
- Update to latest mumble-voip.
- Turn off use2dAudioInVehicles

It appears to happend more often when the players are in MLOs.
Hope the community can find a fix for it.

**Comment by KrisKingo** [comment]
And yeah, this is our onesync settings:
#Onesync
set onesync legacy
set onesync on
set onesync_workaround763185 true

set onesync_forceMigration true
set onesync_distanceCullVehicles true

**Comment by SteveBaggins** [comment]
Did you fix this?

**Comment by oussamaelhajoui** [comment]
Whats the fix to this?
