### ISSUE TITLE
People going global on artifact 3184.

### ISSUE THREAD

**Issue by KrisKingo** [FrazzIe/mumble-voip-fivem#105]
People are going global on the artifact version 3184.
Those anyone know which artifact that supports the latest version of txAdmin works with mumble-voip?
That doesn't have the global problem?

**Comment by Kawium** [comment]
I have same issue.

**Comment by GGCHades** [comment]
Has anyone found a sollution to this. I have had to stop using Mumble and switch to Toko as it was really bad

**Comment by KrisKingo** [comment]
We found out that if you switch proximity... it helps. So if you make a consisten loop of it switching back and forth it fixes the problem :D

**Comment by CarlBishop** [comment]
Same issue also with 3364. Did someone found a fix?

**Comment by KrisKingo** [comment]
Check the message over?

**Comment by oussamaelhajoui** [comment]
> Check the message over?
This is very unclear on how you fixed it..

**Comment by KrisKingo** [comment]
> > Check the message over?
> > This is very unclear on how you fixed it..

How can it be unclear?
I said you should make a loop that resets you proximity, and then your voice wouldn't go global as many times.
But we don't have problems with global voices anymore, so i dont think you need to do this.

**Comment by eltison** [comment]
Can you explain in detail to us ignorant how to do it?
Because the problem persists
