### ISSUE TITLE
Mumble Voip script problem

### ISSUE THREAD

**Issue by Mickey191** [FrazzIe/mumble-voip-fivem#107]
Please can you help me? I have a error a line 15.
![Capture](https://user-images.githubusercontent.com/76750814/103310727-8f5f7380-4a18-11eb-94dd-0976209d2803.PNG)

Thanks

**Comment by JewishRapper** [comment]
is onesync enabled?

**Comment by Mickey191** [comment]
what is Onesync?
 I'm LocalHost

**Comment by Korioz** [comment]
update your server artifacts
