### ISSUE TITLE
warning not connected to mumble

### ISSUE THREAD

**Issue by XOutcastGamingX** [FrazzIe/mumble-voip-fivem#108]
i have read other comments about this and all the answers say check one sync well I did one sync is on and everything and I still get this same error and I need help.

**Comment by Kaparrs** [comment]
same here

**Comment by dfcgaming** [comment]
same here

**Comment by Lap1nas** [comment]
> i have read other comments about this and all the answers say check one sync well I did one sync is on and everything and I still get this same error and I need help.

Same

**Comment by dfcgaming** [comment]
We reinstalled the server and legit just dragged the plugin into the resources and started it. it works now.. dunno but i thing the problem relies on fivem and not on this source.

**Comment by XOutcastGamingX** [comment]
Tried that already as well
