### ISSUE TITLE
Mumble Crash Error

### ISSUE THREAD

**Issue by Kuwu-Git** [FrazzIe/mumble-voip-fivem#110]
I've been having this issue for months now, I have reinstalled my entire computer many times GTA V, FiveM, even went as far as buying a new audio output device!

An error caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.
Stack trace:
  0x0
  voip-mumble.dll!MumbleAudioOutput::InitializeAudioDevice (0x26e) (MumbleAudioOutput.cpp:1217)
  voip-mumble.dll!MumbleAudioOutput::ThreadFunc (0xd2) (MumbleAudioOutput.cpp:1046)
  voip-mumble.dll!<lambda>::operator() (0x101) (MumbleAudioOutput.cpp:202)
  voip-mumble.dll!std::invoke<<lambda> > (0x8) (type_traits:1596)
  voip-mumble.dll!std::thread::_Invoke<std::tuple<<lambda> >,0> (0x3b) (thread:43)
  ucrtbase.dll!beginthreadex (0x141)

**Comment by Kuwu-Git** [comment]
@FrazzIe

**Comment by TommyGun23007** [comment]
im having this same problem rn, and I cant find a fix.

**Comment by TommyGun23007** [comment]
@FrazzIe did you manage to find a fix? i've also reinstalled GTA V and Five M many times but found no solution.
