### ISSUE TITLE
mumble voip down?

### ISSUE THREAD

**Issue by cornly** [FrazzIe/mumble-voip-fivem#112]
Mumble Voip cant connect but onesync is enabled.

**Comment by Oser01** [comment]
For me is still down

**Comment by LoganGeeraerts** [comment]
dose anyone now why my players cant hear me  and i cant hear them?

**Comment by SmokeEnergy** [comment]
Add this : 

Citizen.CreateThread(function()
	while true do 
		Citizen.Wait(500)
			NetworkSetVoiceActive(true)
	end
end)

**Comment by TrueWLAN** [comment]
Wehre to add

**Comment by SmokeEnergy** [comment]
Anywhere on the client side
