### ISSUE TITLE
having problem on not connecting

### ISSUE THREAD

**Issue by joeng2645** [FrazzIe/mumble-voip-fivem#118]
> you don't need the `setr` stuff anymore, it's handle in the config file.
> Are you sure onesync is enabled, that warning only shows up if your voice chat is disabled, or onesync is disabled or your external server is offline

good afternoon sir i read your old post and reply so i realize the post had been close then i just had to open new post..
i been using mumble voip and i dont face any problem at all until yesterday my players complaining that the mumble is not connect as the photo shown below.. my onesynce are all enable as shown on photo number 2

![20210204155659_1](https://user-images.githubusercontent.com/67365019/106863364-601ce000-6703-11eb-9dde-7b5a45c429f3.jpg)
![image](https://user-images.githubusercontent.com/67365019/106863668-cdc90c00-6703-11eb-8b12-c7b0714570ba.png)

**Comment by GaluzaCZ** [comment]
Just use older version. I use the oldest version and works for me :D
