### ISSUE TITLE
mumble-voip is so laggy

### ISSUE THREAD

**Issue by Kristukas1337** [FrazzIe/mumble-voip-fivem#119]
Hello, so in my server mumble-voip is so so laggy, you can barely hear the other people, we bought a new hosting for the server with 16gb ram with 250mb/s internet connection server is linux what can be the problem? We use the newest recommended artifacts, can it be any script that do that to mumble voip?

**Comment by PCFGOSRP** [comment]
hey, i also have a question about it. i was just wondering if you guys have had a problem with the mumble-voip only working in cars, and not normally :( please help with this

**Comment by Kristukas1337** [comment]
No no no, our voip is working everywhere, rp-radio working everything is working, but it just really laggy

**Comment by Kristukas1337** [comment]
And we have that problem after we moved to LS from Paleto Bay :(
