### ISSUE TITLE
Mic / Hearing stopping working and players need to on / off often (alot of times)

### ISSUE THREAD

**Issue by LegendProjects** [FrazzIe/mumble-voip-fivem#121]
Hey as the title saids the mumble have a serious issue, in my server the players have a lot of issues with mumble and they stop hearing or they can't talk they need to on / off microphone 10 times to make it working again, i am not sure what the problem is but when they have that issue the mumble is still connected any clues or help?

**Comment by mindiw01** [comment]
We have the same issue with ESX :/

**Comment by popo8720** [comment]
rt

**Comment by Adam-rGz** [comment]
I have similar problem. Players just stop hearing each other then need to restart voice settings and it works again. No errors

**Comment by bleiker152** [comment]
+1

**Comment by Wrighty0161** [comment]
Same issue, people need to turn voice OFF then ON to get it to work again.

**Comment by Pieg13** [comment]
Same issue, no solution ?

**Comment by Eric13585** [comment]
Habe das selbe Problem
