### ISSUE TITLE
mumble-voip v1.5.5 3d audio [players hearing others randomly across map]

### ISSUE THREAD

**Issue by Repentz** [FrazzIe/mumble-voip-fivem#123]
Framework: Qbus

(Yes, I have removed all proximity scripts)

When 3daudio is enabled, players can sometimes hear eachother across the map.

Using latest stable FXServer

**Comment by FootSoldierZDev** [comment]
Following, as I have the same issue

**Comment by mindiw01** [comment]
We have the same issue on ESX.
If whe disable the 3daudio, the players can hear everything as normal.

**Comment by alberto-rodriguez-muelas** [comment]
I have the same issue, but I can't fix it disabling 3d audio, I need help please.
