### ISSUE TITLE
Error "[Warning] Not connect to mumble" When vMenu voice chat is NOT enabled.

### ISSUE THREAD

**Issue by SerenityRED** [FrazzIe/mumble-voip-fivem#124]
Once I turn off vMenu Voice Chat to utilize Mumble, it seems to stop Mumble from functioning as well.
![image](https://user-images.githubusercontent.com/53364388/107877539-5412ea00-6e8a-11eb-9518-32a5070b5617.png)
![image](https://user-images.githubusercontent.com/53364388/107877543-5e34e880-6e8a-11eb-8161-9aaa4857d11e.png)

**Comment by JamieT0001** [comment]
You need to disable vMenu voice chat as it is a conflict with mumble VC. You can do that by commenting out the voicechat lines in the permissions config file for vMenu
