### ISSUE TITLE
SetPlayerRadioName sample?

### ISSUE THREAD

**Issue by ResqDiver1317** [FrazzIe/mumble-voip-fivem#134]
Has anyone used the export for SetPlayerRadioName successfully? I'm wanting to create a simple command for /setradioname that players can use to enter their own call sign to replace the phonectic that is automatically assigned. Ideally, I want the radio list to show their set callsign/name and their server ID but I can't figure out how to get the export to work. 

My command itself works as I also have it triggering a notification showing them what they set and when I use it, I see that notification, but it's not setting their actual radioname. 

RegisterCommand("setradioname", function(source, args, raw)
	if args[1] ~= nil then
		local Message = table.slice(args, 1)
		Message = table.concat(Message, " ")
			TriggerClientEvent("FeedM:showAdvancedNotification", source, "~b~RADIO NAME SET", GetPlayerName(source), Message, "CHAR_CALL911", "10000", "success")
			exports["mumble-voip"]:SetPlayerRadioName(Message)
	end
end)

**Comment by Jenskuin04** [comment]
if you have found something please let me know cause i want this too and i tried but its not working for me

**Comment by tiagomorais121** [comment]
the problem you have there is simple when you did the exports["mumble-voip"]:SetPlayerRadioName(Message) you forget he source, so you have to do this on a server file: 
exports['mumble-voip']:SetPlayerRadioName(source,Message)
