### ISSUE TITLE
Mic stops working after a while

### ISSUE THREAD

**Issue by Wrighty0161** [FrazzIe/mumble-voip-fivem#135]
After a while people's mics stop working. They can still hear other people but can not be heard.

To fix they need to go into Options>Voice Settings and turn it OFF and back ON.

Has anyone come up with a fix OR workaround for this?

Any help would be appreciated.

Thanks in advance.

**Comment by luislv190998** [comment]
i have the same issue and i cant find how to solve it

**Comment by Lennand** [comment]
Me too, seems Frazzle doesnt work anymore... :((
