### ISSUE TITLE
[ISSUE] Lowered volume when looking straight at someone

### ISSUE THREAD

**Issue by BULLIT33N** [FrazzIe/mumble-voip-fivem#150]
Hi, I have this issue on this server, where when I look straight at someone, the volume lowers, and sometimes I can't even hear them. But when I look obliquely across, I hear them perfectly. Does anyone have a solution to this issue? 

Btw. I have a razer headset, if it has something to do with that! :)

**Comment by Cu-chi-zz** [comment]
Hello, try removing 3D audio in the configuration file and see if it still happens

**Comment by BULLIT33N** [comment]
I’m not completely sure agere the 3D audio is.
