### ISSUE TITLE
Mumble Issue with hearing issue

### ISSUE THREAD

**Issue by RStar84** [FrazzIe/mumble-voip-fivem#151]
The FiveM server I operate off of, started using Mumble last week, and since then I can hear people from across the map, even with my voice range set to "whisper". I'm not sure whats wrong, or how to fix it. Below is a short video showing the issue. 

https://youtu.be/C_tzHxBgpfQ

**Comment by FakeItalianMan** [comment]
Have you found a fix for this? I am having same issue on my server.
