### ISSUE TITLE
[Voice] Initialising & [Warning] Not connected to mumble

### ISSUE THREAD

**Issue by Osinedges** [FrazzIe/mumble-voip-fivem#152]
I haven't configured the mumble voip at all, have dragged it into my server, added to server.cfg and booted and doesn't work. Any troubleshooting steps or things I may have missed?

**Comment by TheTechJess** [comment]
If you are using TXADMIN pls check if you have onesync infinity on, and add to the end of your ServerStarter file “+set onesync_enabled 1”.
https://gyazo.com/8317935237ca3da0c5ddfd93f0bff2e2

**Comment by xd-vape** [comment]
i have the same issue and i have Onesync enabled in txadmin with infinity

**Comment by TsShoyu** [comment]
Same to me, it says initialising and i do have Onesync infinity on

**Comment by FutureEclipse** [comment]
I have the same issue at the moment it was working yesterday and not today
