### ISSUE TITLE
Push to talk stuck on

### ISSUE THREAD

**Issue by SOFcobra** [FrazzIe/mumble-voip-fivem#158]
It seems like every time I join a game with Mumble my voice is stuck on even though I am using push to talk. If I switch to Voice Activity it will only turn on when I talk but with PTT it is constantly on and picks up everything.

**Comment by Reagan831** [comment]
I am having the same issue non stop have not found anyway to fix it yet

**Comment by bigred-ourp** [comment]
i just found the issue is when u tab out of game it locks the mic on.. now to determine how and why

**Comment by HumanTree92** [comment]
Anybody found a fix for this yet. Maybe @FrazzIe do you know how to fix this?

**Comment by mrtylergamer** [comment]
Anyone found anything got the same issue tab out and mic sticks open

**Comment by SOFcobra** [comment]
Yeah no.. Still having issues with tabbing out breaking mumble every now and then.

**Comment by mrtylergamer** [comment]
Update found this on reddit https://www.reddit.com/r/FiveM/comments/ojtphd/pushtotalk_is_voice_activity_for_me/

"I was able to find a fix, So far it appears to be permanent too! In keybinds navigate to the voice chat bind and add a secondary key bind (can be literally anything) and it should fix this!" 

Worked for me still no idea whats broken to start
