### ISSUE TITLE
Mumble Initialising, Not connected to mumble

### ISSUE THREAD

**Issue by sMyLLeX** [FrazzIe/mumble-voip-fivem#160]
![Screenshot 2021-07-30 131809](https://user-images.githubusercontent.com/71394069/127639045-8e441e21-d2a4-4628-9424-04206f956fca.png)
Here is how it looks, i dont use the rp radio, dont think its needed. Im preety sure onesync is on, though i might be mistaken as all i did was add +set onesync on in the server.cfg, could i get some help with this?

**Comment by kulathedev** [comment]
Hey there!

I think what you might want to do is enable OneSync WITH infinity or else it will not work- I had this same issue, yes OneSync might be good and all but for this to work you'll need it with infinity. Hope this helped!

**Comment by Eric13585** [comment]
Hey, i have the same problem and i can not fix this

**Comment by kulathedev** [comment]
> 
> 
> Hey, i have the same problem and i can not fix this

Have you enabled OneSync WITH Infinity?

**Comment by xMaKii** [comment]
same problem, i have infinity...
