### ISSUE TITLE
some bugs in dev mode

### ISSUE THREAD

**Issue by xrtw** [FrazzIe/mumble-voip-fivem#27]
hello, sometimes rp-radio stop working with newest mumble-voip. also sometimes players cant hear each other when speaking together, they need to restart their voice settings and go from other people and come back.
+ when can't hear each other, rp-radio working

**Comment by xrtw** [comment]
driving above 100, can't hear other person who's sitting near.

**Comment by xrtw** [comment]
is it possible to change player default voice when they join to server so quiet? not normal as was before

**Comment by xrtw** [comment]
when you cant hear others, you have to run about 50-80 metres from players, before that you need to restart your voice, and when you come back, you can hear but not every time

**Comment by FrazzIe** [comment]
> when you cant hear others, you have to run about 50-80 metres from players, before that you need to restart your voice, and when you come back, you can hear but not every time

I believe this issue is fixed in the latest version

> driving above 60mph, can't hear other person who's sitting near.

Try this again with the latest release

**Comment by xrtw** [comment]
still some bugs, could i get your discord?
