### ISSUE TITLE
not connected orsomething??

### ISSUE THREAD

**Issue by CrimeLifeRP** [FrazzIe/mumble-voip-fivem#42]
Hello i installed mumble-voip a couple times
and evertime i have problem with it like you can't hear people on radio
voice chat is very sillence by everyone and now this problem i followed all steps

how to fix this one?

https://gyazo.com/c17bad434900dbd9c96f77f9c8997b59
https://gyazo.com/ff58325601296d4dd9e85abca548e35a

**Comment by FrazzIe** [comment]
you don't need the `setr` stuff anymore, it's handle in the config file.
Are you sure onesync is enabled, that warning only shows up if your voice chat is disabled, or onesync is disabled or your external server is offline

**Comment by Havok66** [comment]
> 
> 
> you don't need the `setr` stuff anymore, it's handle in the config file.
> Are you sure onesync is enabled, that warning only shows up if your voice chat is disabled, or onesync is disabled or your external server is offline

Quick question: Why does the new version require OneSync?

**Comment by CrimeLifeRP** [comment]
> you don't need the `setr` stuff anymore, it's handle in the config file.
> Are you sure onesync is enabled, that warning only shows up if your voice chat is disabled, or onesync is disabled or your external server is offline

I fixed it! the onesync is now true only problem i have is just the radio don't show up & doens't work with /radio

**Comment by FrazzIe** [comment]
> > you don't need the `setr` stuff anymore, it's handle in the config file.
> > Are you sure onesync is enabled, that warning only shows up if your voice chat is disabled, or onesync is disabled or your external server is offline
> 
> Quick question: Why does the new version require OneSync?

This script has always required onesync, fivem's mumble implementation on works if onesync is enabled

**Comment by FrazzIe** [comment]
> > you don't need the `setr` stuff anymore, it's handle in the config file.
> > Are you sure onesync is enabled, that warning only shows up if your voice chat is disabled, or onesync is disabled or your external server is offline
> 
> I fixed it! the onesync is now true only problem i have is just the radio don't show up & doens't work with /radio

https://github.com/FrazzIe/rp-radio#note

**Comment by epicgameruk** [comment]
How can I get ESX to work with onesync

**Comment by sicora-dev** [comment]
IMPORTANT¡¡¡ 
you must have over than 32 slots if u r using zap hosting

**Comment by ElixerDevelopment** [comment]
Hello, So it says. Mumble Initialising, Warning Not Connected to mumble.

I have enabled oneSync and it did nothing

**Comment by SheeshGaming420** [comment]
Mine does not work i have one sync enabled and i have myself connected to my mumble server but it still says not connected on my fivem server, ive tried everything even setting my public ip and the port of the server in the "use external server" option in then config still no luck im trying to get gcphone, phone calls to work any help will be loved. thank you.

**Comment by Flo4604** [comment]
I also have set onesync on in my config and it says not connected

**Comment by joeng2645** [comment]
> you don't need the `setr` stuff anymore, it's handle in the config file.
> Are you sure onesync is enabled, that warning only shows up if your voice chat is disabled, or onesync is disabled or your external server is offline

good afternoon sir i been using mumble voip and i dont face any problem at all until yesterday my players complaining that the mumble is not connect as the photo shown below.. my onesynce are all enable as shown on photo number 2

![20210204155659_1](https://user-images.githubusercontent.com/67365019/106863364-601ce000-6703-11eb-9dde-7b5a45c429f3.jpg)
![image](https://user-images.githubusercontent.com/67365019/106863668-cdc90c00-6703-11eb-8b12-c7b0714570ba.png)

**Comment by Lakrlds** [comment]
> > you don't need the `setr` stuff anymore, it's handle in the config file.
> > Are you sure onesync is enabled, that warning only shows up if your voice chat is disabled, or onesync is disabled or your external server is offline
> 
> good afternoon sir i been using mumble voip and i dont face any problem at all until yesterday my players complaining that the mumble is not connect as the photo shown below.. my onesynce are all enable as shown on photo number 2
> 
> ![20210204155659_1](https://user-images.githubusercontent.com/67365019/106863364-601ce000-6703-11eb-9dde-7b5a45c429f3.jpg)
> ![image](https://user-images.githubusercontent.com/67365019/106863668-cdc90c00-6703-11eb-8b12-c7b0714570ba.png)

I have the exact som problem right now, and it happened out of nowhere.
You found a fix?

**Comment by RedEstonia** [comment]
> > > you don't need the `setr` stuff anymore, it's handle in the config file.
> > > Are you sure onesync is enabled, that warning only shows up if your voice chat is disabled, or onesync is disabled or your external server is offline
> > 
> > 
> > good afternoon sir i been using mumble voip and i dont face any problem at all until yesterday my players complaining that the mumble is not connect as the photo shown below.. my onesynce are all enable as shown on photo number 2
> > ![20210204155659_1](https://user-images.githubusercontent.com/67365019/106863364-601ce000-6703-11eb-9dde-7b5a45c429f3.jpg)
> > ![image](https://user-images.githubusercontent.com/67365019/106863668-cdc90c00-6703-11eb-8b12-c7b0714570ba.png)
> 
> I have the exact som problem right now, and it happened out of nowhere.
> You found a fix?

have the same problem any fix yet?
