### ISSUE TITLE
script error: @mumble-voip/client.lua:665: attemp to compare number with nill

### ISSUE THREAD

**Issue by HezimX** [FrazzIe/mumble-voip-fivem#45]
i got this error with this new update

![error](https://user-images.githubusercontent.com/58196256/92047590-c59c2780-ed85-11ea-9811-13693b838b9d.png)

**Comment by Em1tSan** [comment]
I also ran into such a problem when I try to use the radio - the same error appears.

**Comment by FrazzIe** [comment]
this issue *should* be fixed in version 1.5.2

**Comment by HezimX** [comment]
yepp fixed
