### ISSUE TITLE
can't hear people

### ISSUE THREAD

**Issue by CrimeLifeRP** [FrazzIe/mumble-voip-fivem#46]
Hello i did everthing correct but i can't hear people ingame, and my radio doens't show up with the keybinds or /radio

**Comment by FrazzIe** [comment]
https://github.com/FrazzIe/rp-radio#note

**Comment by CrimeLifeRP** [comment]
yea did it but i can't still hear nobody? can you join my discord for checking ? or like fast support i tried some many things

https://invite.gg/crimeliferp
