### ISSUE TITLE
voiceModes broke

### ISSUE THREAD

**Issue by XvenDeR** [FrazzIe/mumble-voip-fivem#47]
With default resource you can't switch back voiceModes. It works 1 time to the "Shouting" and it stops from switching.

**Comment by Oser01** [comment]
I have the same problem. It works 1 time to "Shouting" and then never works again. 
Also, duing this with rp-radio, you can't use the radio.

**Comment by FrazzIe** [comment]
version?

**Comment by XvenDeR** [comment]
Only this, but idk if its related
![image](https://user-images.githubusercontent.com/29688478/92117484-e56f3200-edfd-11ea-90d8-123c11e9fa9f.png)

**Comment by FrazzIe** [comment]
should be fixed with commits 058f3d5def75dd243adcffd2506a221a53a2c5ea and 71906663268ad9fca05005cb3e69960755426643, i'll make a new release in 5 minutes~

**Comment by XvenDeR** [comment]
works perfectly
