### ISSUE TITLE
spectate

### ISSUE THREAD

**Issue by xrtw** [FrazzIe/mumble-voip-fivem#48]
when admin spectates person and stop spectating, player who was spectated can hear him talking

**Comment by FrazzIe** [comment]
This script does not support any type of spectating.

**Comment by xrtw** [comment]
was using this https://github.com/SmokeEnergy/EasyAdmin-Mumble-Voip-

**Comment by FrazzIe** [comment]
1. it's made for an old version of mumble (pre-refactor)
2. I never made it so why should i support it
3. He even included an old version with his changes instead of a pull request
