### ISSUE TITLE
Mumble warning Not connected

### ISSUE THREAD

**Issue by ArneBAR** [FrazzIe/mumble-voip-fivem#51]
Hey i get no errors but it still says [Warning] not connected to mumble
![mumble](https://user-images.githubusercontent.com/67328556/92158099-aeb01080-ee2b-11ea-8ac3-c26cca96ecd5.PNG)

**Comment by FrazzIe** [comment]
duplicate #49 #42

**Comment by Zarriss** [comment]
So, I have seen a lot of people having the same problems, I enabled onsync, and it still says not connected. Could you please update me on the issue?
