### ISSUE TITLE
IDEA : players can see others in same radio

### ISSUE THREAD

**Issue by ali-exacute** [FrazzIe/mumble-voip-fivem#52]
First of all, thank you for all the work you doing for Fivem community.  You are a legend.

My idea is something like discord overlay, to show when somebody is in same radio channel with you
I tried it with drawtext and it is very high usage as would expect..
Thank you

**Comment by FrazzIe** [comment]
![Image](https://i.imgur.com/D9fIvoA.png)

Added it, currently in dev branch seems to work fine, comes with a server side export for setting player names.
