### ISSUE TITLE
server.lua:12: attempt to call  a nil value (global 'GetMaxChunkID'

### ISSUE THREAD

**Issue by LukeeeChan** [FrazzIe/mumble-voip-fivem#53]
Am I missing something???

**Comment by FrazzIe** [comment]
`GetMaxChunkID` is in `grid.lua` and is a script that is loaded on the client and server, maybe your server file is loading for the grid for some reason

**Comment by LukeeeChan** [comment]
is there a way to fix this?

**Comment by LukeeeChan** [comment]
Well I solved it by moving the resource somewhere else, but now I'm not getting any errors but still with;

[Mumble]
[Warning] Not connected to mumble

**Comment by FrazzIe** [comment]
That error comes from having either voice chat disabled in your GTA settings or not running onesync on your server or if you are  trying to use an external server and it's not online

**Comment by LukeeeChan** [comment]
Can you explain, trying to use an external server and it's not online, because I know it's not my GTA serttings nor is it my server not running onesync.

**Comment by FrazzIe** [comment]
you'd know if you are trying to use an external server, you need to set the option manually in the config, so if it's not that then it's one of the first 2 issues.

**Comment by LukeeeChan** [comment]
Yeah, my owner is an idiot, he told me onesync was enabled, went to check, it wasn't. Thank you so much. Sorry for wasting your time.
