### ISSUE TITLE
Can only hear other players while in the same vehicle; they can always hear me

### ISSUE THREAD

**Issue by JoeSzymkowiczFiveM** [FrazzIe/mumble-voip-fivem#56]
The script is running with the default 1.5.3 config settings, and have verified my and the other players settings are identical and mics is working properly. When we ride in the same vehicle, we are able to talk and hear eachother. When we are outside of the vehicle, they can hear me but I no longer hear them. The other player is standing near when outside of vehicles, and should be within distance.

Debug messaages below from the other player getting in and out of the car.
https://i.imgur.com/KNAMffA.png

**Comment by FrazzIe** [comment]
is there a screenshot of player 2's view

**Comment by JoeSzymkowiczFiveM** [comment]
IIRC, screenshot is from Player 1, my pov. Player 2 is seen in right side of screenshot, out of car.

**Comment by FrazzIe** [comment]
i meant console output

**Comment by JoeSzymkowiczFiveM** [comment]
Screenshot is from Player 1 pov.

**Comment by FrazzIe** [comment]
i know but do you have a screenshot of player 2's pov with there console output

**Comment by JoeSzymkowiczFiveM** [comment]
Here are screenshots of us sitting in the car together, player ids are in the lower left hand corner.
https://i.imgur.com/6jlUvKB.png
https://i.imgur.com/1EcMSWy.png

And then we get out of the car.
https://i.imgur.com/w11G6g9.png
https://i.imgur.com/w0HPvxK.png

To add to the weirdness, we had another player jump on, and Player 3 and that person could talk to eachother fine. I am the admin on the server, and they aren't. I'm not sure if that matters. I'm running vMenu 3.2.1 and I know there are voice char settings in there.
https://i.imgur.com/geQfKHk.png

**Comment by FrazzIe** [comment]
vMenu's voice stuff 100% conflicts

**Comment by FrazzIe** [comment]
The screenshots look normal.

**Comment by JoeSzymkowiczFiveM** [comment]
This was the issue!. I disabled the voice chat functionality in vMenu and everyone can hear everyone now. Thank you very much for the help and keep up the great work!
