### ISSUE TITLE
Not Connected to mumble

### ISSUE THREAD

**Issue by MaNtouviosGR** [FrazzIe/mumble-voip-fivem#60]
ok so i recently installed your resource and when i log into my server i get a message that mumble is not connected, can you pls help me fix it?

**Comment by rodney-rightscale** [comment]
Are you running onesync?

**Comment by MaNtouviosGR** [comment]
no. do i have to run onesync or patreon @rodney-rightscale

**Comment by ScorzP** [comment]
> ok so i recently installed your resource and when i log into my server i get a message that mumble is not connected, can you pls help me fix it?

Me to

**Comment by FrazzIe** [comment]
duplicate: #51 #49 #42 
look at issue: #42
