### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sparah** [FrazzIe/mumble-voip-fivem#61]
When I start mumble-voip I get this error: "@mumble-voip/server.lua:15: attempt to call a nil value (global 'MumbleCreateChannel')"

**Comment by FrazzIe** [comment]
Are you on an old server version?

**Comment by Sparah** [comment]
yeah, I'm planning on updating though, so it'll work when I update?

**Comment by XvenDeR** [comment]
Do it and u will see.
