### ISSUE TITLE
Callsigns are duplicated in the Radio List

### ISSUE THREAD

**Issue by Em1tSan** [FrazzIe/mumble-voip-fivem#62]
The latest version "mumble-voip-fivem" has a problem: when you turn off / on Radio, callsigns are duplicated in the Radio List. Each time the radio is switched on, as well as when switching to a new frequency, a new line appears in the Radio List.

In addition, you cannot turn off the display of the Radio List.
showRadioList = false,
But the Radio List is still displayed for players.

**Comment by FrazzIe** [comment]
what line is appearing exactly?

**Comment by Em1tSan** [comment]
Always different.
Here's an example: https://imgur.com/a/tkESCrN

**Comment by FrazzIe** [comment]
![gif](https://i.imgur.com/JjrSGaV.gif)

Turning the radio on and off seems to work fine, am i missing something here?

**Comment by ClarkGriffen** [comment]
Having same problem it dosent disrepair when turning on/off it just add another one with same name
