### ISSUE TITLE
External mumble server is not working correctly

### ISSUE THREAD

**Issue by Em1tSan** [FrazzIe/mumble-voip-fivem#67]
I'm testing the use of an external server, according to the instructions: 

I am testing using an external server, according to the instructions: https://forum.cfx.re/t/how-to-host-fivems-voice-chat-mumble-in-another-server/1487449?u=frazzle

There is a problem: during normal conversation, the players cannot hear each other. When using a walkie-talkie and a telephone, they hear, but it comes with an interruption, slower.

**Comment by Em1tSan** [comment]
![Безымянный](https://user-images.githubusercontent.com/70670181/93327149-958f6280-f822-11ea-95aa-16f159a02e15.jpg)

**Comment by procoder4** [comment]
pls swich to alt v or rage mp

**Comment by procoder4** [comment]
use 
setr voice_use3dAudio true
setr voice_useSendingRangeOnly true
