### ISSUE TITLE
The player hears other players while riding the bike.

### ISSUE THREAD

**Issue by Em1tSan** [FrazzIe/mumble-voip-fivem#69]
We noticed a strange problem: if a player is on a bike, he can hear other players on the other ends of the map.

mumble-voip: v1.5.5
FXServer 2949 (Linux) with OneSync Infinty/Beyond
Players: 30+
Convars:

set onesync_distanceCullvehicles true
set onesync_forceMigration true
set onesync_workaround763185 true

**Comment by piratajr** [comment]
Same here - 200+ players - 1.5.5 - 2949 windows
