### ISSUE TITLE
Insanely minor nitpick

### ISSUE THREAD

**Issue by sjennison** [FrazzIe/mumble-voip-fivem#7]
So, technically on a trunked radio system (one where you would get the talk-permit tone), you would not have an MDC1200 chirp at the end of the transmission (MDC1200's primary purpose is essentially made redundant in a TRS). Assuming you somehow *had* MDC on a TRS, you also wouldn't hear it at the end of your own transmission (subscriber units don't broadcast their MDC PTT-ID tails), you'd only hear it from other subscribers.

A realistic end-of-transmission sound would be a SpectraTAC comparator click like the one I've attached here - those would be heard at the end of your and anyone else's transmissions.

[eot_click.zip](https://github.com/FrazzIe/mumble-voip/files/4396639/eot_click.zip)

**Comment by FrazzIe** [comment]
I know absolutely nothing about radios.

**Comment by sjennison** [comment]
I figured - it's a niche hobby.

Basically, the talk permit tone (mic_on) and MDC1200 chirp (mic_off) wouldn't be heard together IRL. You also would never hear mic_off from your own radio when you let off the mic. The sound I attached would be realistic in both those scenarios, if you want to use that though.
