### ISSUE TITLE
Mumble not working no errors radio fine

### ISSUE THREAD

**Issue by sonicbroadcasting** [FrazzIe/mumble-voip-fivem#74]
ok so have +set onesync on have done it with and without setr voice_use3dAudio true
setr voice_useSendingRangeOnly true. have disabled and enabled vmenu voicechat. everyone could hear people global so changed onesync to what it is now, now no one can hear each other or see mouths moving. Radio works fine but mumble voip just isnt. Any idea? no error codes at all for it

**Comment by NylanderrDK** [comment]
I have the same issue - you found a fix?
