### ISSUE TITLE
Players can't hear each other

### ISSUE THREAD

**Issue by RedEstonia** [FrazzIe/mumble-voip-fivem#76]
Hello,
Players cant hear each other in the server but when they are in the car or using gcphone, rp-radio they can...

can you help me?

**Comment by fantomeus** [comment]
same here :/

**Comment by gonibix23** [comment]
same for me

**Comment by gonibix23** [comment]
> Hello,
> Players cant hear each other in the server but when they are in the car or using gcphone, rp-radio they can...
> 
> can you help me?

Did find out the problem?

**Comment by apyxpi** [comment]
same problem.. The voip is working in cars and in phone calls but not as usual.

**Comment by gonibix23** [comment]
I have solved the problem, voice chat vMenu, disable it and will work

**Comment by sonicbroadcasting** [comment]
> I have solved the problem, voice chat vMenu, disable it and will work

Tried this by deleting and just commenting it all out. What did you do?

**Comment by gonibix23** [comment]
> > I have solved the problem, voice chat vMenu, disable it and will work
> 
> Tried this by deleting and just commenting it all out. What did you do?

Just commenting in permissions.cfg  the lines of the voice chat so any admin can use it worked to me.

**Comment by sonicbroadcasting** [comment]
> > > I have solved the problem, voice chat vMenu, disable it and will work
> > 
> > 
> > Tried this by deleting and just commenting it all out. What did you do?
> 
> Just commenting in permissions.cfg the lines of the voice chat so any admin can use it worked to me.
making voice chat in vmenu admin only?
