### ISSUE TITLE
Voice not working outside of a vehicle, unless inside of a vehicle

### ISSUE THREAD

**Issue by tysonfry1** [FrazzIe/mumble-voip-fivem#79]
radio works perfectly fine inside and outside of vehicle, although we can not speak to each other in voice chat unless inside of a vehicle.. we do not have vMenu and the menu we use doesnt have anything to do with voice disabling of anything. Wondering if you would know of anything about this i know about the vMenu stuff messing with the voice but we dont run off of that

**Comment by apyxpi** [comment]
I am having the same problem

**Comment by Xorbite** [comment]
Having the same issue here, radio is working perfectly

**Comment by Swahgner** [comment]
Having the same issue - tried restarting GTA voice settings, enable/disable vMenu voice chat - nothing works

**Comment by Swahgner** [comment]
We found a soloution:
If you have vMenu installed, go in permissions.cfg and comment out every line in the voice chat section.
Make sure you do a restart after saving the file.
