### ISSUE TITLE
OneSync Infinity

### ISSUE THREAD

**Issue by WooAf** [FrazzIe/mumble-voip-fivem#8]
It doesn't actually work with infinity, might need to fix this

Sometime when we are not in the same instance we can hear each others and when we're not in the same instance we can't hear anyone from radio or phone

**Comment by FrazzIe** [comment]
I currently see no way of fixing it for infinity. it was never intended for it.

**Comment by WooAf** [comment]
What do you mean it is not intended for it ? your script or mumble in general ? I currently have a custom build of tokovoip that works with onesync so I guess its possible for mumble too

**Comment by FrazzIe** [comment]
My script was not intended to work on OneSync infinity

**Comment by mickeygeecom** [comment]
Very good job on this script @FrazzIe 

We're currently trying to make it support Infinity with this new native implemented to FiveM.
https://github.com/citizenfx/fivem/commit/9cbbb45f2cfd41b1176f7f41017a20e55f85b796

and this PR coming soon, hopefully!
https://github.com/citizenfx/fivem/pull/408

**Comment by WooAf** [comment]
Would be great !

**Comment by PichotM** [comment]
it won't fix anything

**Comment by PichotM** [comment]
@FrazzIe I've added voice target by server id, it should bring infinity support

**Comment by SeneXDeveloper** [comment]
@PichotM So you got it work with Infinity? Do you have Discord or something?

**Comment by filipe4fun** [comment]
> Very good job on this script @FrazzIe
> 
> We're currently trying to make it support Infinity with this new native implemented to FiveM.
> [citizenfx/fivem@9cbbb45](https://github.com/citizenfx/fivem/commit/9cbbb45f2cfd41b1176f7f41017a20e55f85b796)
> 
> and this PR coming soon, hopefully!
> [citizenfx/fivem#408](https://github.com/citizenfx/fivem/pull/408)

We also need to make this work for infinity! Would you mind sharing your progress?

**Comment by DMachad0** [comment]
any update ?

**Comment by mickeygeecom** [comment]
We currently launched our radios for Infinity into production last night. We started to encounter performance/hitch issues around ~70+ players.

Stuff is working, but hitching is uncool, so we're looking into optimizing now. 😎

**Comment by fredyy27** [comment]
Any update about onesync infinity? :)

**Comment by BugCode1** [comment]
![unknown](https://user-images.githubusercontent.com/26005436/82730633-5c346380-9d16-11ea-889a-4552ab5a2924.png)

Testing mumble voip on infinity with 100+ players,
1.60 < 2.50 cpu msec and its bad

**Comment by ali-exacute** [comment]
> ![unknown](https://user-images.githubusercontent.com/26005436/82730633-5c346380-9d16-11ea-889a-4552ab5a2924.png)
> 
> Testing mumble voip on infinity with 100+ players,
> 1.60 < 2.50 cpu msec and its bad

Its not bad for what its doing and 100+ players

**Comment by BugCode1** [comment]
> Its not bad for what its doing and 100+ players

Yeah, its because mumbleoverridebyserverid for all players in all frames, actually can't be optimized

**Comment by fredyy27** [comment]
Could you send that release so we can test in our server with 150 players?

**Comment by uncleilia** [comment]
f

**Comment by uncleilia** [comment]
I just pressed f to pay my respect to this dissociation
really have nothing else to say at this point

**Comment by dkdknight** [comment]
an infinity version would be much appreciated. with regard to the concerns of ms can be to privilege a solution in rtc

**Comment by cadox8** [comment]
Hello, @mickeygeecom @BugCode1, do you have any updates?

**Comment by makfcb** [comment]
Does anyone have any idea how to get it working in OneSync Infinity?

**Comment by KAWAIY-GH** [comment]
any updates?

**Comment by FrazzIe** [comment]
The refactor i'm working on in the dev branch might be compatible with onesync infinity.

**Comment by Vivi4n** [comment]
Working on my own refactoring based off of your dev branch. One small issue is that the native MumbleAddVoiceTargetPlayerByServerId crashes out, as a voice target isn't specified within the function SetPlayerTargets() and a few other places.

**Comment by FrazzIe** [comment]
> Working on my own refactoring based off of your dev branch. One small issue is that the native MumbleAddVoiceTargetPlayerByServerId crashes out, as a voice target isn't specified within the function SetPlayerTargets() and a few other places.

Fixed this like 2 hours ago, was wondering why i kept getting an error, completely forgot it takes to params.

Everything should be working, only feature missing is hearing peoples radio/calls (loudspeaker thingy)

**Comment by Vivi4n** [comment]
Having an issue hearing people over radios, but I assume it's local for now. Will give it a few more rounds of testing and review later.

Thanks bunches (:

**Comment by FrazzIe** [comment]
I can only test with myself and a virtual machine running the game spamming music through voicemeter. I was able to here my virtual machines music just fine on the radio. So if there is an issue hopefully you find a repro or the fix.

**Comment by TehRamsus** [comment]
> I can only test with myself and a virtual machine running the game spamming music through voicemeter. I was able to hear my virtual machines music just fine on the radio. So if there is an issue hopefully you find a repro or the fix.

Hey. Have you some discord? I want to ask some question about that virtual machine :D

**Comment by FrazzIe** [comment]
> > I can only test with myself and a virtual machine running the game spamming music through voicemeter. I was able to hear my virtual machines music just fine on the radio. So if there is an issue hopefully you find a repro or the fix.
> 
> Hey. Have you some discord? I want to ask some question about that virtual machine :D

frazzle#6627
