### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by brentN5** [FrazzIe/mumble-voip-fivem#82]

**Comment by ghost** [comment]
has been having this happen to us too.

**Comment by custardyfingers** [comment]
Its better. But there are still players experiencing global effects but a lot less with use2dAudioInVehicles.

**Comment by kFxDaKing** [comment]
We got same problem

**Comment by ghost** [comment]
can confirm even when disabling use2daudioinvehicles

that sometimes players can hear ecother on global. a temp fixed seems to be to make them enable and disable voice again.

**Comment by custardyfingers** [comment]
I can confirm this as well.

**Comment by ghost** [comment]
Are you all using the latest version?

im wondering if we all could use a previous version

**Comment by custardyfingers** [comment]
I was using the latest version . But I reverted to an old modified version that I did when it first came out.

**Comment by tflorimo** [comment]
My players report that when you're in a car with someone, if you get out of it, you keep hearing that person "globally".
3D audio DISABLED, use2dAudioInVehicles ENABLED. Patiently waiting for updates.
