### ISSUE TITLE
Mumble initialising with onesync enabled

### ISSUE THREAD

**Issue by raffycaccia** [FrazzIe/mumble-voip-fivem#85]
Hi, I'm using onesync up to 48 slots so not the one with the patreon argentum level, the server tells me that onesync is enabled as per photo, but mumble keeps giving me the initialising message
![gregregerrge](https://user-images.githubusercontent.com/45554975/97110819-94800980-16db-11eb-9a19-78adbe246cb0.PNG)
![grgergergreg](https://user-images.githubusercontent.com/45554975/97110821-9518a000-16db-11eb-98a9-be4252a06050.PNG)
![fffff](https://user-images.githubusercontent.com/45554975/97110822-95b13680-16db-11eb-9a65-8caa03037d45.PNG)

**Comment by StaffTP** [comment]
Did you find a fix to this?
