### ISSUE TITLE
Players can't hear or talk

### ISSUE THREAD

**Issue by leocrvg** [FrazzIe/mumble-voip-fivem#90]
radio is going fine, but when people want to talk in a street for example, the voice stop working, I test in a car and go well.
I see some fixing envolving disable vMenu but in my server I don't have this.

**Comment by AleDema** [comment]
I usually fix this by restarting voice chat in GTA settings, no idea what causes it.

**Comment by Swahgner** [comment]
> I usually fix this by restarting voice chat in GTA settings, no idea what causes it.

I have the exact same issue, tried restarting the voice chat in GTA settings, but didn't fix it :/

**Comment by Swahgner** [comment]
We found a soloution:
If you have vMenu installed, go in permissions.cfg and comment out every line in the voice chat section.
Make sure you do a restart after saving the file.

**Comment by AleDema** [comment]
But @leocrvg doesnt use it

**Comment by leocrvg** [comment]
@Swahgner @AleDema guys, unfortunately I had to back to mumble old version, my server can't stop, but I continue w radio

**Comment by JSanchezFDZ** [comment]
Same problem 👎

**Comment by Jaccosf** [comment]
Have this too, yesterday it worked completely fine, now it is broken.

**Comment by VictorColome** [comment]
Found out that this happens when activating the useNativeAudio feature. Any fix for this?

**Comment by sMyLLeX** [comment]
it probably interferes with another voice chat script ex:vmenu etc.. so just disable it and it should work i think
