### ISSUE TITLE
Hear everyone when loading into the server

### ISSUE THREAD

**Issue by UnknownNuggz** [FrazzIe/mumble-voip-fivem#92]
When there are lots of players on the server and you connect, when loading, depending on how fast you load in you can hear every single person speaking, its quite frustrating when people have metagamed from this. Once you actually spawn in game, its then fine and you cant hear anyone unless they are next to you of course, functionality is perfecct after loading in.

This happenes just after the awaiting scripts message at the bottom right of the screeen

**Comment by AvarianKnight** [comment]
add `NetworkSetTalkerProximity(3.0)` in one of the citizen.CreateThreads

**Comment by eltison** [comment]
Hi 🖖
Could you explain us how to fix this ? 
wich files to edit ? Where to ?
