### ISSUE TITLE
mumble voip - "initializing"

### ISSUE THREAD

**Issue by andrevaz15** [FrazzIe/mumble-voip-fivem#96]
![Screenshot_1](https://user-images.githubusercontent.com/73839623/99112986-0b733880-25de-11eb-9180-81dbc9c234a6.png)

**Comment by StaffTP** [comment]
Have you found a fix?

**Comment by andrevaz15** [comment]
> Have you found a fix?

I didn't

**Comment by bennetde** [comment]
Anyone got something? What exactly is this a duplicate of?
