### ISSUE TITLE
Warning not connected to mumble.

### ISSUE THREAD

**Issue by StaffTP** [FrazzIe/mumble-voip-fivem#97]
This is not a duplicate! I have onesync enabled and I have looked for two days for a fix, Nothing. Any help?

**Comment by FrazzIe** [comment]
look here: https://github.com/FrazzIe/mumble-voip-fivem/issues/42
If this doesn't help, oh well. currently not working on fivem.

**Comment by KRISSX6D** [comment]
Hi! I have zap hosting  server (32 slots) and if i put this ressource on, then it says its not connected. :/
