### ISSUE TITLE
Cloakroom to go on duty

### ISSUE THREAD

**Issue by Intelligentzombie29** [FrazzIe/mumble-voip-fivem#98]
Hey, i went through the whole script and cant find this, but im looking to change how i get access to private radio channels, currently police and EMS have to go to the cloakroom and select a uniforn, any ideas how i would change this so it runs off the ESX_duty script, so when they go on duty it will allow them access into the private channels

**Comment by iSentrie** [comment]
Same way as they get it at cloakroom.

**Comment by AvarianKnight** [comment]
@tom091291 This is something you have to make on your own, it's not provided with the script.

**Comment by GamenHaaDee** [comment]
Citizen.CreateThread(function ()
  while true do
    Citizen.Wait(0)

      local playerPed = GetPlayerPed(-1)

    if CurrentAction ~= nil then
      SetTextComponentFormat('STRING')
      AddTextComponentString(CurrentActionMsg)
      DisplayHelpTextFromStringLabel(0, 0, 1, -1)

      if IsControlPressed(0, Keys['E']) then
        if CurrentAction == 'ambulance_duty' then
          if PlayerData.job.name == 'ambulance' or PlayerData.job.name == 'offambulance' then
            TriggerServerEvent('duty:ambulance')
          if PlayerData.job.name == 'ambulance' then
            sendNotification(_U('offduty'), 'success', 2500)
            exports["rp-radio"]:RemovePlayerAccessToFrequencies(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
            Wait(1000)
          else
            sendNotification(_U('onduty'), 'success', 2500)
            exports["rp-radio"]:GivePlayerAccessToFrequencies(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
            Wait(1000)
          end
        else
          sendNotification(_U('notamb'), 'error', 5000)
          Wait(1000)
        end
      end
